filetype off
call pathogen#runtime_append_all_bundles()
filetype plugin indent on

set backspace=2

" Pretty settings
set number
set ts=4 sts=2 sw=2 expandtab
set wrap
set linebreak

" From vimcasts.org
" Hold command and press navigation key inorder to navigate to apparent 
" lines.
vmap <D-j> gj
vmap <D-k> gk
vmap <D-4> g$
vmap <D-6> g^
vmap <D-0> g^
nmap <D-j> gj
nmap <D-k> gk
nmap <D-4> g$
nmap <D-6> g^
nmap <D-0> g^

nmap <silent> <Leader>t :CommandT<CR>

syntax on
set nocp
filetype plugin on
filetype indent on
set guifont=DejaVu\ Sans\ Mono:h20
" If not gui
colorscheme Vitamins_Vim_Colorscheme_by_hcalves
" Color Scheme (only if GUI running)
if has("gui_running")
  colorscheme Vitamins_Vim_Colorscheme_by_hcalves
  set guifont=DejaVu\ Sans\ Mono:h14
endif

function Do256()
    " Enable 256 colors
    set t_Co=256
    set t_AB=[48;5;%dm
    set t_AF=[38;5;%dm
endfu

function UnDo256()
    " Enable 256 colors
    set t_Co &vim 
    set t_AB &vim
    set t_AF &vim
endfu

com! -nargs=* Color256 exe Do256()
com! -nargs=* UnColor256 exe UnDo256()

let g:rubycomplete_buffer_laoding = 1
let g:rubycomplete_classes_in_global = 1
let g:rubycomplete_rails = 1

if has("autocmd") && exists("+omnifunc")
autocmd Filetype *
        \	if &omnifunc == "" |
        \		setlocal omnifunc=syntaxcomplete#Complete |
        \	endif
endif
set noswapfile


command W w !sudo tee % > /dev/null

if &diff
  colorscheme evening
endif
